修复项目脚本在低版本bash上运行出错的bug

diff --git a/trunk/tools/gadt-mkhtml b/trunk/tools/gadt-mkhtml
--- a/trunk/tools/gadt-mkhtml
+++ b/trunk/tools/gadt-mkhtml
@@ -212,14 +212,17 @@ ARGLIST=$@
 # Parse Command Line Options.
 OPT_SHORT="bcCefhHilLmnop:rst"
 OPT_LONG="browser,clean,cleancache,fuzzy,editsgml,reviewsgml,list,mergepo,install,nodeps,noextract,noconfigure,nosgml,nohtmlhelp,help,log,nobuild"
-# Pacman Options
-OPT_TEMP="$(parse_options $OPT_SHORT $OPT_LONG "$@" || echo 'PARSE_OPTIONS FAILED')"
+# Options
+# OPT_TEMP="$(parse_options $OPT_SHORT $OPT_LONG "$@" || echo 'PARSE_OPTIONS FAILED')"
+OPT_TEMP="$(getopt -o "$OPT_SHORT" -l "$OPT_LONG" -n "$(basename "$0")" -- "$@" || echo 'PARSE_OPTIONS FAILED')"
 if echo "$OPT_TEMP" | grep -q 'PARSE_OPTIONS FAILED'; then
 	# This is a small hack to stop the script bailing with 'set -e'
 	echo; usage; exit 1 # E_INVALID_OPTION;
 fi
 eval set -- "$OPT_TEMP"
 unset OPT_SHORT OPT_LONG OPT_TEMP
+
+
 
 while true; do
 	case "$1" in
